# Site settings
title: Radi Hilaneh
email: radihilaneh@gmail.com
description: "Portfolio of Radi Hilaneh. Creative Coder.Multimedia and interaction Designer."

social:
  twitter: "http://twitter.com/"
  linkedin: "https://www.linkedin.com/in/radihilaneh/"
  instagram: "https://www.instagram.com/f33r/"
  github: "https://github.com/JessieSpike"
  500px: "https://500px.com/"
baseurl:  # the subpath of your site, e.g. /blog
url: http://radihilaneh.com # the base hostname & protocol for your site

# collections:
collections:
  portfolio:
    output: true
    permalink: /:collection/:title/index.html
  categories:
    output: true
#default
defaults:
  -
    scope:
      path: ""
      type: categories
    values:
      layout: "category"
# Build settings
markdown: kramdown

plugins:
  - jekyll-paginate
  - jekyll-compose

paginate: 6
paginate_path: "blog/page:num"
